// src/constants/GeneratorConstants.ts

export const GENERATOR_CONSTANTS = {
    DEFAULT_GAS_LIMIT: 1000000,
    REACTIVE_IGNORE: '0xa65f96fc951c35ead38878e0f0b7a3c744a6f5ccc1476b313353ce31712313ad',
    SERVICE_ADDRESS: '0x0000000000000000000000000000000000fffFfF',
    TEMPLATE_PLACEHOLDERS: {
        BASE_CONTRACT: '{{BASE_CONTRACT}}',
        ORIGIN_CHAIN_ID: '{{ORIGIN_CHAIN_ID}}',
        DESTINATION_CHAIN_ID: '{{DESTINATION_CHAIN_ID}}',
        ORIGIN_CONTRACT: '{{ORIGIN_CONTRACT}}',
        DESTINATION_CONTRACT: '{{DESTINATION_CONTRACT}}',
        EVENT_CONSTANTS: '{{EVENT_CONSTANTS}}',
        SUBSCRIPTIONS: '{{SUBSCRIPTIONS}}',
        REACT_LOGIC: '{{REACT_LOGIC}}',
        STATE_VARIABLES: '{{STATE_VARIABLES}}',
        PROTOCOL_IMPORTS: '{{PROTOCOL_IMPORTS}}',
        PROTOCOL_INTERFACES: '{{PROTOCOL_INTERFACES}}'
    },
    SUPPORTED_SOLIDITY_VERSIONS: ['>=0.8.0'],
    DEFAULT_OPTIMIZATION_RUNS: 200
};